project_id = "vczrkqwnokjuxehvbrbx"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.delete-user]
    verify_jwt = false
  [functions.increment-virtual-participants]
    verify_jwt = false
  [functions.notify-telegram]
    verify_jwt = false
  [functions.notify-wholesale-lead]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.reset-weekly-orders]
    verify_jwt = false
  [functions.send-email]
    verify_jwt = false
  [functions.signup-with-email]
    verify_jwt = false
  [functions.sync-products]
    verify_jwt = false
